# Generated by Django 5.2.5 on 2026-06-04 13:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionETL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(choices=[('famosos', 'Famosos'), ('lugares', 'Lugares'), ('comunas', 'Comunas')], max_length=20, verbose_name='Dataset Procesado')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de término')),
                ('registros_leidos', models.IntegerField(default=0, verbose_name='Registros leídos')),
                ('registros_procesados', models.IntegerField(default=0, verbose_name='Registros procesados')),
                ('duplicados_eliminados', models.IntegerField(default=0, verbose_name='Duplicados eliminados')),
                ('registros_consolidados', models.IntegerField(default=0, verbose_name='Registros consolidados')),
                ('registros_no_encontrados', models.IntegerField(default=0, verbose_name='Registros no encontrados')),
                ('errores', models.IntegerField(default=0, verbose_name='Cantidad de errores')),
            ],
            options={
                'verbose_name': 'Ejecución ETL',
                'verbose_name_plural': 'Ejecuciones ETL',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.CharField(max_length=200, verbose_name='Nombre original')),
                ('nombre_normalizado', models.CharField(help_text='Nombre limpio y estandarizado para control de duplicados (RF-03, RF-04).', max_length=200, unique=True, verbose_name='Nombre normalizado')),
                ('region', models.CharField(blank=True, help_text='Obtenido de fuente externa (RF-05, RF-06).', max_length=200, null=True, verbose_name='Región')),
                ('habitantes', models.IntegerField(blank=True, help_text='Obtenido de fuente externa (RF-05, RF-06).', null=True, verbose_name='Cantidad de habitantes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada en')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'ordering': ['nombre_normalizado'],
                'indexes': [models.Index(fields=['nombre_normalizado'], name='etl_app_com_nombre__ce33d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(choices=[('famosos', 'Famosos (DATOS2026-2.txt)'), ('lugares', 'Lugares (DATOS2026-3.TXT)')], max_length=20, verbose_name='Dataset de origen')),
                ('linea_numero', models.IntegerField(verbose_name='Número de línea')),
                ('contenido_original', models.TextField(verbose_name='Contenido original de la línea')),
                ('tipo_error', models.CharField(choices=[('fecha_invalida', 'Fecha inválida o histórica'), ('fecha_aproximada', 'Fecha aproximada (alrededor de...)'), ('formato_invalido', 'Formato de línea incorrecto'), ('coordenada_invalida', 'Coordenada fuera de rango'), ('encoding', 'Error de encoding'), ('duplicado', 'Registro duplicado'), ('otro', 'Otro error')], default='otro', max_length=30, verbose_name='Tipo de error')),
                ('mensaje_error', models.TextField(verbose_name='Mensaje de error detallado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Detectado en')),
            ],
            options={
                'verbose_name': 'Error de importación',
                'verbose_name_plural': 'Errores de importación',
                'ordering': ['-created_at', 'dataset', 'linea_numero'],
                'indexes': [models.Index(fields=['dataset', 'tipo_error'], name='etl_app_err_dataset_6c9fba_idx')],
            },
        ),
        migrations.CreateModel(
            name='Famoso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Nombre normalizado (sin numeración inicial)', max_length=200, verbose_name='Nombre completo')),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha en formato estándar. NULL si la fecha no pudo parsearse.', null=True, verbose_name='Fecha de nacimiento')),
                ('fecha_original', models.CharField(help_text='Texto exacto de la fecha tal como apareció en el archivo.', max_length=100, verbose_name='Fecha original (TXT)')),
                ('edad_actual', models.IntegerField(blank=True, help_text='Calculada automáticamente desde fecha_nacimiento.', null=True, verbose_name='Edad actual')),
                ('esta_de_cumpleanos', models.BooleanField(default=False, help_text='True si hoy coincide con el día y mes de nacimiento.', verbose_name='¿Está de cumpleaños hoy?')),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de la imagen')),
                ('imagen_fuente', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fuente de la imagen')),
                ('imagen_fecha', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fecha de captura/publicación de imagen')),
                ('es_fecha_aproximada', models.BooleanField(default=False, help_text='True si la fecha no pudo parsearse (ej: "alrededor de 1162", "69 a.C.").', verbose_name='¿Fecha aproximada o histórica?')),
                ('hash_registro', models.CharField(help_text='SHA-256 calculado sobre nombre_normalizado + fecha_original.', max_length=64, unique=True, verbose_name='Hash único del registro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Famoso',
                'verbose_name_plural': 'Famosos',
                'ordering': ['nombre_completo'],
                'indexes': [models.Index(fields=['nombre_completo'], name='etl_app_fam_nombre__6154ae_idx'), models.Index(fields=['fecha_nacimiento'], name='etl_app_fam_fecha_n_22222c_idx'), models.Index(fields=['esta_de_cumpleanos'], name='etl_app_fam_esta_de_3619a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lugar', models.CharField(max_length=200, verbose_name='Nombre del lugar')),
                ('descripcion', models.TextField(blank=True, default='', help_text='Campo reservado para enriquecer el lugar con info adicional.', verbose_name='Descripción')),
                ('hash_registro', models.CharField(help_text='SHA-256 sobre nombre_normalizado + direccion_completa.', max_length=64, unique=True, verbose_name='Hash único')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'ordering': ['nombre_lugar'],
                'indexes': [models.Index(fields=['nombre_lugar'], name='etl_app_lug_nombre__66aa7a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Georeferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, help_text='Rango válido: -90.0 a 90.0', max_digits=9, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=6, help_text='Rango válido: -180.0 a 180.0', max_digits=9, verbose_name='Longitud')),
                ('lugar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='georeferencia', to='etl_app.lugar', verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'Georeferencia',
                'verbose_name_plural': 'Georeferencias',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_calle', models.CharField(blank=True, default='', max_length=300, verbose_name='Nombre de la calle / vía')),
                ('numero_calle', models.CharField(blank=True, default='', max_length=50, verbose_name='Número')),
                ('comuna', models.CharField(blank=True, default='', max_length=150, verbose_name='Comuna')),
                ('ciudad', models.CharField(blank=True, default='', max_length=150, verbose_name='Ciudad')),
                ('ciudad_estado_provincia', models.CharField(blank=True, default='', max_length=200, verbose_name='Ciudad / Estado / Provincia')),
                ('pais', models.CharField(blank=True, default='', max_length=100, verbose_name='País')),
                ('direccion_completa', models.TextField(verbose_name='Dirección completa (original normalizada)')),
                ('lugar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direccion', to='etl_app.lugar', verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
    ]
