# Generated by Django 5.2.8 on 2026-06-04 02:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionETL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(choices=[('famosos', 'Famosos'), ('lugares', 'Lugares'), ('comunas', 'Comunas')], max_length=20, verbose_name='Dataset Procesado')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de término')),
                ('registros_leidos', models.IntegerField(default=0, verbose_name='Registros leídos')),
                ('registros_procesados', models.IntegerField(default=0, verbose_name='Registros procesados')),
                ('duplicados_eliminados', models.IntegerField(default=0, verbose_name='Duplicados eliminados')),
                ('registros_consolidados', models.IntegerField(default=0, verbose_name='Registros consolidados')),
                ('registros_no_encontrados', models.IntegerField(default=0, verbose_name='Registros no encontrados')),
                ('errores', models.IntegerField(default=0, verbose_name='Cantidad de errores')),
            ],
            options={
                'verbose_name': 'Ejecución ETL',
                'verbose_name_plural': 'Ejecuciones ETL',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='famoso',
            name='imagen_fecha',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fecha de captura/publicación de imagen'),
        ),
        migrations.AddField(
            model_name='famoso',
            name='imagen_fuente',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fuente de la imagen'),
        ),
        migrations.AddField(
            model_name='famoso',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de la imagen'),
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.CharField(max_length=200, verbose_name='Nombre original')),
                ('nombre_normalizado', models.CharField(help_text='Nombre limpio y estandarizado para control de duplicados (RF-03, RF-04).', max_length=200, unique=True, verbose_name='Nombre normalizado')),
                ('region', models.CharField(blank=True, help_text='Obtenido de fuente externa (RF-05, RF-06).', max_length=200, null=True, verbose_name='Región')),
                ('habitantes', models.IntegerField(blank=True, help_text='Obtenido de fuente externa (RF-05, RF-06).', null=True, verbose_name='Cantidad de habitantes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada en')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'ordering': ['nombre_normalizado'],
                'indexes': [models.Index(fields=['nombre_normalizado'], name='etl_app_com_nombre__ce33d6_idx')],
            },
        ),
    ]
