# Generated by Django 5.2.8 on 2026-06-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0002_ejecucionetl_famoso_imagen_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='comuna',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Comuna'),
        ),
    ]
